# Generated by Django 4.0.3 on 2022-03-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Write author's name", max_length=100, verbose_name="Author's name")),
                ('last_name', models.CharField(help_text="Write author's lastname", max_length=100, verbose_name="Author's lastname")),
                ('date_of_birth', models.DateField(blank=True, help_text="Write author's date of birth", null=True, verbose_name="Author's date of birth")),
                ('date_of_death', models.DateField(blank=True, help_text="Write author's date of death", null=True, verbose_name="Author's date of death")),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Write title', max_length=200, verbose_name="Book's title")),
                ('summary', models.TextField(help_text="Write book's summary", max_length=1000, verbose_name='Annotation')),
                ('isbn', models.CharField(help_text='Should write 13 characters', max_length=13, verbose_name='ISBN')),
                ('author', models.ManyToManyField(help_text="Write book's author", null=True, to='catalog.author', verbose_name="Book's author")),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Write book's genre", max_length=200, verbose_name="Book's genre")),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Write book's language", max_length=20, verbose_name="Book's language")),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Write status', max_length=200, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.CharField(help_text='Write inventory number', max_length=20, null=True, verbose_name='Inventory number')),
                ('imprint', models.CharField(help_text='Write publisher and year of publishing', max_length=200, verbose_name='Publisher and year of publishing')),
                ('due_back', models.DateField(blank=True, help_text='Write status end date ', null=True, verbose_name='Status end date')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text="Change book's status", null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Status')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text="Write book's genre", null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name="Book's genre"),
        ),
    ]
