# Generated by Django 3.2.10 on 2022-03-11 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='borrowed',
            field=models.ForeignKey(blank=True, help_text='Choose customer', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
    ]
